apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountserver
  namespace: t1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountserver
  template:
    metadata:
      labels:
        app: accountserver
    spec:
      initContainers:
        - name: migrate-db
          image: martinsglucas/t1-accountserver:latest
          command: ["npx", "prisma", "migrate", "deploy"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: client-db-url
                  key: DATABASE_URL
      containers:
        - name: accountserver
          image: martinsglucas/t1-accountserver:latest
          ports:
            - containerPort: 50052
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: client-db-url
                  key: DATABASE_URL
          readinessProbe:
            tcpSocket:
              port: 50052
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 50052
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: accountserver
  namespace: t1
spec:
  selector:
    app: accountserver
  ports:
    - port: 50052
      targetPort: 50052
  type: ClusterIP