apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alt-postgres-pvc
  namespace: t1
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alt-postgres
  namespace: t1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alt-postgres
  template:
    metadata:
      labels:
        app: alt-postgres
    spec:
      containers:
      - name: alt-postgres
        image: postgres:15
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: alt-postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: alt-postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: alt-postgres-secret
              key: POSTGRES_DB
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pgdata
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: alt-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: alt-postgres
  namespace: t1
spec:
  selector:
    app: alt-postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP