apiVersion: v1
kind: Secret
metadata:
  name: alt-client-db-url
  namespace: t1
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzcHdAYWx0LXBvc3RncmVzOjU0MzIvY2xpZW50ZGI=
---
apiVersion: v1
kind: Secret
metadata:
  name: alt-postgres-secret
  namespace: t1
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgrespw
  POSTGRES_DB: clientdb