apiVersion: apps/v1
kind: Deployment
metadata:
  name: alt-accountserver
  namespace: t1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alt-accountserver
  template:
    metadata:
      labels:
        app: alt-accountserver
    spec:
      initContainers:
        - name: migrate-db
          image: martinsglucas/t1-alt-accountserver:latest
          command: ["npx", "prisma", "migrate", "deploy"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: alt-client-db-url
                  key: DATABASE_URL
      containers:
        - name: alt-accountserver
          image: martinsglucas/t1-alt-accountserver:latest
          ports:
            - containerPort: 50052
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: alt-client-db-url
                  key: DATABASE_URL
            - name: CLIENT_SERVICE_URL
              value: "http://alt-clientserver:50051"
          readinessProbe:
            tcpSocket:
              port: 50052
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 50052
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: alt-accountserver
  namespace: t1
spec:
  selector:
    app: alt-accountserver
  ports:
    - port: 50052
      targetPort: 50052
  type: ClusterIP