apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientserver
  namespace: t1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clientserver
  template:
    metadata:
      labels:
        app: clientserver
    spec:
      initContainers:
        - name: migrate-db
          image: martinsglucas/t1-clientserver:latest
          command: ["npx", "prisma", "migrate", "deploy"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: client-db-url
                  key: DATABASE_URL
      containers:
        - name: clientserver
          image: martinsglucas/t1-clientserver:latest
          ports:
            - containerPort: 50051
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: client-db-url
                  key: DATABASE_URL
          readinessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: clientserver
  namespace: t1
spec:
  selector:
    app: clientserver
  ports:
    - port: 50051
      targetPort: 50051
  type: ClusterIP
