apiVersion: v1
kind: Secret
metadata:
  name: client-db-url
  namespace: t1
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzcHdAcG9zdGdyZXM6NTQzMi9jbGllbnRkYg==
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: t1
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgrespw
  POSTGRES_DB: clientdb