apiVersion: apps/v1
kind: Deployment
metadata:
  name: stub
  namespace: t3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stub
  template:
    metadata:
      labels:
        app: stub
    spec:
      containers:
      - name: stub
        image: martinsglucas/t1-webserver-stub:latest
        ports:
        - containerPort: 8000
        env:
        - name: CLIENT_GRPC_HOST
          value: "clientserver"
        - name: CLIENT_GRPC_PORT
          value: "50051"
        - name: ACCOUNT_GRPC_HOST
          value: "accountserver"
        - name: ACCOUNT_GRPC_PORT
          value: "50052"
        readinessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: stub-service
  namespace: t3
spec:
  selector:
    app: stub
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30080
  type: NodePort